export const loginPath = () => "/login";
export const registerPath = () => "/register";
export const landingPath = () => "/";
export const aboutPath = () => "/about";
export const blogPath = () => "/blog";
export const appBasePath = () => "/app";
export const appHomePath = () => appBasePath();
export const appMePath = () => appBasePath() + "/me";
export const appServersCreatePath = () => appBasePath() + "/servers/create";
export const appInvitesListPath = () => appBasePath() + "/invites";
